In [2]:
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt


# Notebook 1
## April 24/4/2025
This is a notebook to show some basics of array manipulation with `numpy`. It creates arrays to do simple operations like adding two numbers: $x_1+x_2$

You can include complex math:
$$\frac{\partial h}{\partial t}=U-K_fA^mS^n$$

In [3]:
print(1+1)

2


In [6]:
x = [0,1,2,3,4]
x

[0, 1, 2, 3, 4]

In [7]:
x + x

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [8]:
npx = np.array([0,1,2,3,4])
npx

array([0, 1, 2, 3, 4])

In [10]:
npx + npx

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(101)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(23)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [13]:
one = np.ones(22)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.])

In [14]:
one[11]

1.0

In [15]:
x = np.linspace(0,1,11)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [16]:
x[2]

0.2

In [17]:
x[0]

0.0

In [18]:
x[10]

1.0

In [19]:
x[-1]

1.0

In [20]:
x[-2]

0.9

In [21]:
x[0:3]

array([0. , 0.1, 0.2])

In [22]:
x[4:9]

array([0.4, 0.5, 0.6, 0.7, 0.8])

In [23]:
x[4:9:2]

array([0.4, 0.6, 0.8])

In [24]:
x[::]

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [25]:
x[::-1]

array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0. ])

In [26]:
x[1:]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [27]:
x[:-1]

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [29]:
x[1:] - x[:-1]

array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [30]:
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [34]:
x2 = np.ones((5,4,6))
x2

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [35]:
x2 = np.ones((5,4))
x2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
x2[4,3]

1.0

In [38]:
x2[2:4,1:3]

array([[1., 1.],
       [1., 1.]])

In [41]:
x3 = np.random.random((5,4))
x3

array([[0.72276594, 0.72347916, 0.55273168, 0.39606812],
       [0.79886395, 0.85588911, 0.4164246 , 0.97465759],
       [0.58379719, 0.53466268, 0.24760081, 0.10928338],
       [0.37604708, 0.35572212, 0.13031538, 0.97765627],
       [0.44124295, 0.63640842, 0.39846565, 0.73244741]])

In [42]:
x3[2:4,1:3]

array([[0.53466268, 0.24760081],
       [0.35572212, 0.13031538]])